---
title: "Making age structure data by province"
output: html_document
date: "2023-02-24"
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
library(dplyr)
library(tidyr)
library(purrr)
library(terra)
library(stringr)
```

## Downloading data from WorldPop

WorldPop URL:

```{r}
worldpop <- "https://data.worldpop.org/"
```

Local data folder:

```{r}
data_folder <- "~/OneDrive - Oxford University Clinical Research Unit/GitHub/OUCRU-Modelling/aes/WorldPop/"
```

All the combinations of years, ages and gender:

```{r}
combinations <- expand_grid(years = 2000:2020,
                            ages  = c(0, 1, seq(5, 80, 5)),
                            sexes = c("f", "m"))
```

Creating the files names:

```{r}
files_names <- with(combinations,
                    paste0("GIS/AgeSex_structures/Global_2000_2020/",
                           years, "/VNM/vnm_", sexes, "_", ages, "_", years, ".tif"))
```

Creating the folder structure within the data folder:

```{r}
files_names %>% 
  map_chr(str_remove, "/v.*$") %>% 
  unique() %>% 
  paste0(data_folder, .) %>% 
  walk(dir.create, recursive = TRUE)
```

The remote and local files paths:

```{r}
urls <- paste0(worldpop, files_names)
destfiles <- paste0(data_folder, files_names)
```

Downloading the data:

```{r}
walk2(urls, destfiles, download.file)
```

## Generating province data

```{r}
a <- rast(destfiles[1])
```

```{r}
"~/OneDrive - Oxford University Clinical Research Unit/GitHub/aes/GIS/AgeSex_structures/Global_2000_2020/2000/VNM/vnm_f_0_2000.tif"
```

